### ISSUE TITLE
ObjectsMappers - not found

### ISSUE THREAD

**Issue by rareMaxim** [mauriziodm/DJSON#4]
in sample PerformanceTest.dproj - IDE cant find unit "ObjectsMappers".
> [dcc32 Fatal Error] Model.pas(6): F2613 Unit 'ObjectsMappers' not found.

**Comment by mauriziodm** [comment]
'ObjectMappers' is a unit from DMVC Framework project by Daniele Teti and his staff.
It's not included with DJSON.
Basically that project I need to compare performance with this mapper.
DJSON is faster.
